x-build-settings: &build-settings
  USERNAME: developer
  USER_UID: 1000
  USER_GID: 1000
x-volumes: &volumes
  - dev-home:/home/developer
  - ../build/zshrc:/home/developer/.zshrc
  - ~/.config/dotbot/home/config/neovim/:/home/developer/.config/nvim
  - ${PROJECT_PATH_HOST}:${PROJECT_PATH_CONTAINER} 
x-environment: &environment
  - PROJECT_PATH=${PROJECT_PATH_CONTAINER}

volumes:
  dev-home:
    name: dev-home

services:
  zig:
    build: 
      context: ../
      dockerfile: containers/zig/Dockerfile
      args:
        BUILD_DIR: containers/zig/
        MINISIGN_VERSION: "0.12"
        ZIG_VERSION: "0.14.1"
        ZLS_VERSION: "0.14.0"
        <<: *build-settings
    image: dev/zig
    container_name: dev-zig
    volumes: *volumes
    environment: *environment

